### ISSUE TITLE
local variable 'fps' referenced before assignment

### ISSUE THREAD

**Issue by yamizukin** [doakey3/Bligify#4] opened 2017-09-15 16:58 UTC
I got this today and tried this on two gifs so far. One kept giving me this error on my project in progress:

Traceback (most recent call last):
File "C\Users\...\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\Bligify-master\operators\importgif.py", line 147, in execute adjust_scene_for_gif(context, abspath, frames_folder)
File "C\Users\...\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\Bligify-master\operators\importgif.py", line 57, in adjust_scene_for_gif
scene.render.fps = fps
UnboundLocalError: localvariable 'fps' referenced before assignment

So I started a new project, and I ran into the same error. However, another gif imported flawlessly. Please let me know what I may have done to run into this error.

Blender 2.78c, Windows 10

**Comment by doakey3** [comment] 2017-09-15 17:35
When you import an animated GIF, Bligify runs an executable called 'gifsicle' that breaks the gif apart into separate images as well as a text file that has information about the GIF (like the framerate, or fps). Bligify reads the text file and sets the Blender scene's FPS base on that, but it looks like this process failed for some reason.

Would you mind sending me a copy of the animated GIF that failed to import so I can experiment with it and see what went wrong? You can send it to github.dmodo@spamgourmet.com or provide me a download link. Thanks.

**Comment by doakey3** [comment] 2017-09-16 18:15
I made a temporary fix for this. The fps for the scene will be set to 10 for imported GIFs of an unknown FPS. However, I'd still like to figure out why the script was unable to acquire the FPS using your example GIF.

**Comment by doakey3** [comment] 2017-11-04 15:47
The temporary fix will have to do. The problem is that the GIF you were using doesn't store it's fps information in a way that gifsicle can read.

**Closed as completed by doakey3** 2017-11-04 15:47 UTC
